spring:
  jackson:
    time-zone: Asia/Seoul
logging:
  file:
    name: logs/app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS,Asia/Seoul} [%thread] %-5level %logger{36} traceId=%X{traceId} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS,Asia/Seoul} [%thread] %-5level %logger{36} traceId=%X{traceId} - %msg%n"